const dialogues = {
    0: {
        dialogue: [
            {   speaker: '段菲', 
                position: 'left', 
                avatar: 'img/2gf.jpg', 
                text: `小可愛～醒醒～`,
            },
            {   speaker: '', 
                position: 'right', 
                avatar: 'img/1me.jpg', 
                text: `嗯……`,
            },
            {   speaker: '段菲', 
                position: 'left', 
                avatar: 'img/2gf.jpg', 
                text: `早安啊小雲。`,
            },
            {   speaker: '', 
                position: 'right', 
                avatar: 'img/1me.jpg', 
                text: `嗯～好香，好想整天抱著～`,
            },
            {   speaker: '段菲', 
                position: 'left', 
                avatar: 'img/2gf.jpg', 
                text: `我也想，但沒有時間啊，去洗漱吧。`,
            },
            {   speaker: '', 
                position: 'center', 
                avatar: '', 
                text: `
                《換衣服 洗漱》
                `,
            },
            {   speaker: '段菲', 
                position: 'left', 
                avatar: 'img/2gf.jpg', 
                text: `不行，多少吃一點！`,
            },
            {   speaker: '', 
                position: 'right', 
                avatar: 'img/1me.jpg', 
                text: `好啦好啦……
                        哼嗯～好好吃。`,
            },
            {   speaker: '段菲', 
                position: 'left', 
                avatar: 'img/2gf.jpg', 
                text: `好吃就多吃點。`,
            },
            {   speaker: '段菲', 
                position: 'left', 
                avatar: 'img/2gf.jpg', 
                text: `對了～我們什麼時候要回去跟大家一起吃個飯？`,
            },
        ],
        options: [
            { choice: "1", text: "回去" },
            { choice: "2", text: "不回去" },
        ]
    },
        1: {//回去
            dialogue: [
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `等我下班我們就一起回去好不好？`,
                },
                {   speaker: '段菲', 
                    position: 'left', 
                    avatar: 'img/2gf.jpg', 
                    text: `好～`,
                },
                {   speaker: '', 
                    position: 'center', 
                    avatar: '', 
                    text: `
                    公司
                    《人聲和打字聲》
                    `,
                },
                {   speaker: '虎哥', 
                    position: 'left', 
                    avatar: 'img/6npc.jpg', 
                    text: `闕雲啊～晚上下班要不要和我們一起去吃東西？`,
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `不行欸虎哥,晚上要陪菲菲。`,
                },
                {   speaker: '虎哥', 
                    position: 'left', 
                    avatar: 'img/6npc.jpg', 
                    text: `行吧行吧陪陪女朋友也好,哪像我,一把年紀了還是一個人。`,
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `沒事啦～虎哥人那麼好一定找得到！`,
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `哈啊～要接菲菲回去吃飯了。`,
                },
                {   speaker: '', 
                    position: 'center', 
                    avatar: '', 
                    text: `
                    《車子停車聲和關車門的聲音》
                    `,
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `我們回來了！`,
                },
                {   speaker: '高婷', 
                    position: 'left', 
                    avatar: 'img/3mom.jpg', 
                    text: `哎呀，菲菲來啦！進來坐快點！我們才剛開始吃呢！`,
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `欸媽，妳女兒我就站在旁邊欸！不理一下嗎？！`,
                },
                {   speaker: '高婷', 
                    position: 'left', 
                    avatar: 'img/3mom.jpg', 
                    text: `不重要啦哎呦～`,
                },
                {   speaker: '', 
                    position: 'center', 
                    avatar: '', 
                    text: `
                    《筷子碰撞聲》
                    `,
                },
                {   speaker: '高婷', 
                    position: 'left', 
                    avatar: 'img/3mom.jpg', 
                    text: `菲菲啊，這個多吃點，很好吃的。`,
                },
                {   speaker: '段菲', 
                    position: 'left', 
                    avatar: 'img/2gf.jpg', 
                    text: `謝謝阿姨～`,
                },
                {   speaker: '闕華', 
                    position: 'left', 
                    avatar: 'img/4bro.jpg', 
                    text: `小雲啊，上次那個誰來著，他還有來煩妳嗎？`,
                },
            ],
            options: [
                { choice: "1", text: "激動" },
                { choice: "3", text: "反駁" },
            ]
        },
            11:{//激動
                dialogue:[
                    {   speaker: '', 
                        position: 'right', 
                        avatar: 'img/1me.jpg', 
                        text: `吃飯！吃飯！一定要講到他嗎！破壞氣氛欸哥。`,
                    },
                    {   speaker: '闕華', 
                        position: 'left', 
                        avatar: 'img/4bro.jpg', 
                        text: `好啦好啦，他如果又來妳要跟哥講欸！`,
                    },
                    {   speaker: '', 
                        position: 'right', 
                        avatar: 'img/1me.jpg', 
                        text: `知道啦。`,
                    },
                    {   speaker: '', 
                        position: 'center', 
                        avatar: '', 
                        text: `
                        《筷子碰撞聲》
                        `,
                    },
                    {   speaker: '', 
                        position: 'center', 
                        avatar: '', 
                        text: `
                        《電話鈴聲》
                            《掛斷》
                                `,
                    },
                    {   speaker: '高婷', 
                        position: 'left', 
                        avatar: 'img/3mom.jpg', 
                        text: `誰啊？`,
                    },
                    {   speaker: '', 
                        position: 'right', 
                        avatar: 'img/1me.jpg', 
                        text: `沒事推銷的。`,
                    },
                    {   speaker: '', 
                        position: 'center', 
                        avatar: '', 
                        text: `
                        《電話鈴聲》
                        `,
                    },
                    
                ],
                options: [
                    {choice:'1', text: '掛斷'},
                    {choice:'3', text: '接起來'},
                ]
            },
            12:{//反駁
                dialogue:[
                    {   speaker: '', 
                        position: 'right', 
                        avatar: 'img/1me.jpg', 
                        text: `不是啊，上次回來講到他就吵架了，這次為什麼還要再提啊？！`, 
                    },
                    {   speaker: '闕華', 
                        position: 'left', 
                        avatar: 'img/4bro.jpg', 
                        text: `哥就只是問問，怕妳受委屈了。`, 
                    },
                    {   speaker: '段菲', 
                        position: 'left', 
                        avatar: 'img/2gf.jpg', 
                        text: `小雲，沒事了 ，吃飯吧。`, 
                    },
                    {   speaker: '', 
                        position: 'center', 
                        avatar: '', 
                        text: `
                        《電話鈴聲》
                        `,
                    },

                ],
                options: [
                    {choice:'1', text: '掛斷'},
                    {choice:'3', text: '接起來'},
                ]
            },
                13:{//掛斷
                    dialogue:[
                        {   speaker: '高婷', 
                            position: 'left', 
                            avatar: 'img/3mom.jpg', 
                            text: `接一下吧。`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `不用。`, 
                        },
                        {   speaker: '', 
                            position: 'center', 
                            avatar: '', 
                            text: `
                            《電話鈴聲》
                            `,
                        },
                        {   speaker: '高婷', 
                            position: 'left', 
                            avatar: 'img/3mom.jpg', 
                            text: `妳看人家一直打說不定有重要的事。`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `我就說不用了！`, 
                        },
                        {   speaker: '', 
                            position: 'center', 
                            avatar: '', 
                            text: `
                            《推開椅子的聲音》
                            `,
                        },
                        {   speaker: '高婷', 
                            position: 'left', 
                            avatar: 'img/3mom.jpg', 
                            text: `這孩子最近脾氣怎麼這麼大？`, 
                        },
                        {   speaker: '闕華', 
                            position: 'left', 
                            avatar: 'img/4bro.jpg', 
                            text: `媽，沒事啦，小雲可能只是壓力太大。`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `抱歉阿姨，我去看一下她。`, 
                        },
                        {   speaker: '', 
                            position: 'center', 
                            avatar: '', 
                            text: `
                            (臥室裡)
                                《電話鈴聲》
                                    `,
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `你到底想幹嘛！？我已經掛很多通了你還不懂！`, 
                        },
                        {   speaker: '迪克', 
                            position: 'left', 
                            avatar: 'img/5ex.jpg', 
                            text: `沒啊，我看一下你最近過的好不好而已。`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `不可能只是這樣！到底想幹嘛？！之前欠你的是都還清了嗎？`, 
                        },
                        {   speaker: '迪克', 
                            position: 'left', 
                            avatar: 'img/5ex.jpg', 
                            text: `是還了沒錯，但我沒說過不會有利息啊。`, 
                        },
                        {   speaker: '', 
                            position: 'center', 
                            avatar: '', 
                            text: `
                            《掛斷》
                            `,
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `他誰？`, 
                        },
                    ],
                    options: [
                        {choice:'1', text: '含糊帶過'},
                        {choice:'3', text: '老實交代'},
                    ]
                },
                    131:{//含糊帶過 >BE
                        dialogue:[
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `沒啦，就之前一個朋友。`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `朋友會講這種話嗎？`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `就只是之前的朋友，連妳也要這樣嗎？`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `我哪樣？我是妳女友欸，不能知道嗎？`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `女友又怎樣？難道妳是我女友我一切事情就一定要跟妳說嗎？`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `妳一定要這個態度嗎？我們可以好好講的？`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `好好講？剛開始好好講不就好了。`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `妳這個態度我真的不知道怎麼跟妳溝通，之前就發生過一次了。`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `受不了妳就走啊！沒人逼妳。`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `妳真的要說這種話嗎？
                                        那我們就分手吧 既然這麼嫌棄的話。`, 
                            },
                            {   speaker: '', 
                                position: 'center', 
                                avatar: '', 
                                text: `
                                《關門聲》
                                `, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `……`
                            },
                        ],
                        options: []
                    },                    
                    132:{//老實交代 >HE
                        dialogue:[
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `他是前男友，分手時發生點狀況，我砸破了一個古董花瓶，然後就被抓到尾巴了。`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `這樣也要計較，小氣的男人。`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `哈哈哈！就我們菲菲最大方。`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `當然啊！`, 
                            },
                            {   speaker: '', 
                                position: 'center', 
                                avatar: '', 
                                text: `
                                （回家後）
                                `,
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `菲菲閉上眼睛一下。`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `幹嘛～那麼神秘？`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `快點啦～`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `什麼啦？搞得好像要求婚一樣。`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `好了，睜開眼吧。`, 
                            },
                        //change求婚畫面
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `這！什麼啊！`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `段菲小姐，妳願意嫁給闕雲小姐嗎？`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `太突然了吧！`, 
                            },
                        ],
                        options: []
                    },

                14:{//接起來
                    dialogue:[
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `怎樣！找我幹嘛？`, 
                        },
                        {   speaker: '迪克', 
                            position: 'left', 
                            avatar: 'img/5ex.jpg', 
                            text: `沒啊 我看一下你最近過的好不好而已。`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `到底想幹嘛 之前欠你的是都還清了嗎？`, 
                        },
                        {   speaker: '迪克', 
                            position: 'left', 
                            avatar: 'img/5ex.jpg', 
                            text: `是還了沒錯 但我沒說過不會有利息啊。`, 
                        },
                        {   speaker: '', 
                            position: 'center', 
                            avatar: '', 
                            text: `
                            《電話掛斷》
                            `, 
                        },
                        {   speaker: '高婷', 
                            position: 'left', 
                            avatar: 'img/3mom.jpg', 
                            text: `他喔。`, 
                        },
                    ],
                    options: [
                        {choice:'1', text: '含糊帶過'},
                        {choice:'3', text: '承認'},
                    ]
                },
                    141:{//含糊帶過
                        dialogue:[
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `沒啦，一個朋友。`, 
                            },
                            {   speaker: '闕華', 
                                position: 'left', 
                                avatar: 'img/4bro.jpg', 
                                text: `一定不可能啦！`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `吃你的飯吧。`, 
                            },
                            {   speaker: '', 
                                position: 'center', 
                                avatar: '', 
                                text: `
                                        《開車回家後走進家門》
                                        《開車回家後走進家門》
                                        
                                《開車回家後走進家門》
                                        
                                `, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `嗯～今天月亮好圓喔。`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `嗯啊～`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `好希望每天都這樣。`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `嗯……`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `我在想啊……剛剛那通電話是誰啊？`, 
                            },
                        ],
                        options: [
                            {choice:'1', text: '含糊帶過'},
                            {choice:'3', text: '老實交代'},
                        ]
                    },
                    142:{//承認
                        dialogue:[
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `對啦是他啦。`, 
                            },
                            {   speaker: '闕華', 
                                position: 'left', 
                                avatar: 'img/4bro.jpg', 
                                text: `又來！欸妹，我說真的，妳解決不了真的要叫哥。`, 
                            },
                            {   speaker: '高婷', 
                                position: 'left', 
                                avatar: 'img/3mom.jpg', 
                                text: `菲菲啊我跟妳說，她啊從小就是這樣固執，每次都被拋棄，哭的要死要活喔。`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `哈哈哈，阿姨放心，我不會拋棄她的。`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `咳……媽吃飯吧。`, 
                            },
                            {   speaker: '', 
                                position: 'center', 
                                avatar: '', 
                                text: `
                                        《開車回家後走進家門》
                                        《開車回家後走進家門》
                                        
                                《開車回家後走進家門》
                                        
                                `, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `嗯～今天月亮好圓喔～～`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `嗯啊。`, 
                            },
                            {   speaker: '', 
                                position: 'right', 
                                avatar: 'img/1me.jpg', 
                                text: `好希望每天都這樣。`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `嗯……`, 
                            },
                            {   speaker: '段菲', 
                                position: 'left', 
                                avatar: 'img/2gf.jpg', 
                                text: `我在想啊……剛剛那通電話是誰啊？`, 
                            },
                        ],
                        options: [
                            {choice:'1', text: '含糊帶過'},
                            {choice:'3', text: '老實交代'},
                        ]
                    },
                        151:{//含糊帶過 >BE
                            dialogue:[
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `沒啦，就之前一個朋友。`, 
                                },
                                {   speaker: '段菲', 
                                    position: 'left', 
                                    avatar: 'img/2gf.jpg', 
                                    text: `朋友會講這種話嗎？`, 
                                },
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `就只是之前的朋友，連妳也要這樣嗎？`, 
                                },
                                {   speaker: '段菲', 
                                    position: 'left', 
                                    avatar: 'img/2gf.jpg', 
                                    text: `我哪樣？我是妳女友欸，不能知道嗎？`, 
                                },
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `女友又怎樣？難道妳是我女友我一切事情就一定要跟妳說嗎？`, 
                                },
                                {   speaker: '段菲', 
                                    position: 'left', 
                                    avatar: 'img/2gf.jpg', 
                                    text: `妳一定要這個態度嗎？我們可以好好講的？`, 
                                },
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `好好講？剛開始好好講不就好了。`, 
                                },
                                {   speaker: '段菲', 
                                    position: 'left', 
                                    avatar: 'img/2gf.jpg', 
                                    text: `妳這個態度我真的不知道怎麼跟妳溝通，之前就發生過一次了。`, 
                                },
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `受不了妳就走啊！沒人逼妳。`, 
                                },
                                {   speaker: '段菲', 
                                    position: 'left', 
                                    avatar: 'img/2gf.jpg', 
                                    text: `妳真的要說這種話嗎？既然這麼嫌棄的話，那我們就分手吧。`, 
                                },
                                {   speaker: '', 
                                    position: 'center', 
                                    avatar: '', 
                                    text: `
                                            《關門聲》
                                            《關門聲》
                                            
                                    《關門聲》
                                            
                                    `, 
                                },
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `……`
                                },
                            ],
                            options: []
                        },                    
                        152:{//老實交代
                            dialogue:[
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `他是前男友，分手時發生點狀況，我砸破了一個古董花瓶，然後就被抓到尾巴了。`, 
                                },
                                {   speaker: '段菲', 
                                    position: 'left', 
                                    avatar: 'img/2gf.jpg', 
                                    text: `這樣也要計較，小氣的男人。`, 
                                },
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `哈哈哈！就我們菲菲最大方。`, 
                                },
                                {   speaker: '段菲', 
                                    position: 'left', 
                                    avatar: 'img/2gf.jpg', 
                                    text: `當然啊！`, 
                                },
                                {   speaker: '', 
                                    position: 'center', 
                                    avatar: '', 
                                    text: ` 
                                    （回家後）
                                    `,
                                },
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `菲菲閉上眼睛一下。`, 
                                },
                                {   speaker: '段菲', 
                                    position: 'left', 
                                    avatar: 'img/2gf.jpg', 
                                    text: `幹嘛～那麼神秘？`, 
                                },
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `快點啦～`, 
                                },
                                {   speaker: '段菲', 
                                    position: 'left', 
                                    avatar: 'img/2gf.jpg', 
                                    text: `什麼啦？搞得好像要求婚一樣？`, 
                                },
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `好了，睜開眼吧。`, 
                                },
                            //change求婚畫面
                                {   speaker: '段菲', 
                                    position: 'left', 
                                    avatar: 'img/2gf.jpg', 
                                    text: `這！什麼啊！`, 
                                },
                                {   speaker: '', 
                                    position: 'right', 
                                    avatar: 'img/1me.jpg', 
                                    text: `段菲小姐，妳願意嫁給闕雲小姐嗎？`, 
                                },
                                {   speaker: '段菲', 
                                    position: 'left', 
                                    avatar: 'img/2gf.jpg', 
                                    text: `太突然了吧！`, 
                                },
                            ],
                            options: [
                                {choice:'1', text: '逗一下'},
                                {choice:'3', text: '認真的再問一次'},
                            ]
                        },                    
                            1521:{//逗一下 >HE
                                dialogue:[
                                    {   speaker: '', 
                                        position: 'right', 
                                        avatar: 'img/1me.jpg', 
                                        text: `不要嗎？不要就算了。`, 
                                    },
                                    {   speaker: '段菲', 
                                        position: 'left', 
                                        avatar: 'img/2gf.jpg', 
                                        text: `欸欸欸！我願意！`, 
                                    },
                                ],
                                options: []
                            },                    
                            1522:{//認真的再問一次 >HE
                                dialogue:[
                                    {   speaker: '', 
                                        position: 'right', 
                                        avatar: 'img/1me.jpg', 
                                        text: `請問段菲小姐？妳願意嫁給闕雲小姐嗎？`, 
                                    },
                                    {   speaker: '段菲', 
                                        position: 'left', 
                                        avatar: 'img/2gf.jpg', 
                                        text: `我願意。`, 
                                    },
                                    {   speaker: '', 
                                        position: 'right', 
                                        avatar: 'img/1me.jpg', 
                                        text: `嘿嘿嘿，我也知道妳不會拒絕。`, 
                                    },
                                    {   speaker: '段菲', 
                                        position: 'left', 
                                        avatar: 'img/2gf.jpg', 
                                        text: `如果我拒絕呢？`, 
                                    },
                                    {   speaker: '', 
                                        position: 'right', 
                                        avatar: 'img/1me.jpg', 
                                        text: `拒絕的話我就跪到妳答應啊！`, 
                                    },
                                    {   speaker: '段菲', 
                                        position: 'left', 
                                        avatar: 'img/2gf.jpg', 
                                        text: `最好是。`, 
                                    },
                                ],
                                options: []
                            },

                        
                        

        2: {//不回去
            dialogue: [
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `這次先不回去了吧。`, 
                },
                {   speaker: '段菲', 
                    position: 'left', 
                    avatar: 'img/2gf.jpg', 
                    text: `好吧，累了就先休息一下吧。`, 
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `那我先出門啦！`, 
                },
                {   speaker: '段菲', 
                    position: 'left', 
                    avatar: 'img/2gf.jpg', 
                    text: `路上小心喔～`, 
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `會啦！`, 
                },
                {   speaker: '', 
                    position: 'center', 
                    avatar: '', 
                    text: `
                    公司
                    《人聲和打字聲》
                    `, 
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `等我下班我們就一起回去好不好？`,
                },
                {   speaker: '段菲', 
                    position: 'left', 
                    avatar: 'img/2gf.jpg', 
                    text: `好～`,
                },
                {   speaker: '', 
                    position: 'center', 
                    avatar: '', 
                    text: `
                     公司
                     《人聲和打字聲》
                     `,
                },
                {   speaker: '虎哥', 
                    position: 'left', 
                    avatar: 'img/6npc.jpg', 
                    text: `闕雲啊～晚上下班要不要和我們一起去吃東西？`,
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `不行欸虎哥,晚上要陪菲菲。`,
                },
                {   speaker: '虎哥', 
                    position: 'left', 
                    avatar: 'img/6npc.jpg', 
                    text: `行吧行吧陪陪女朋友也好,哪像我,一把年紀了還是一個人。`,
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `哈哈哈哈，你今天是怎樣啦，工作完再懷疑人生啦。`,
                },
                {   speaker: '虎哥', 
                    position: 'left', 
                    avatar: 'img/6npc.jpg', 
                    text: `闕雲！安慰一下會少一塊肉是不是！`,
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `沒事啦～虎哥人那麼好一定找得到！`,
                },
                {   speaker: '虎哥', 
                    position: 'left', 
                    avatar: 'img/6npc.jpg', 
                    text: `……果然還是闕雲會安慰人。`,
                },
                {   speaker: '', 
                    position: 'right', 
                    avatar: 'img/1me.jpg', 
                    text: `哈哈哈哈哈哈。`,
                },
                {   speaker: '', 
                    position: 'center', 
                    avatar: '', 
                    text: `
                            《人聲和打字聲越來越少》
                            《人聲和打字聲越來越少》


                    《人聲和打字聲越來越少》


                            家門外
                            家門外


                    家門外


                    《電話鈴聲》`
                    ,
                },
            ],
            options: [
                {choice:'1', text: '接通'},
                {choice:'3', text: '掛斷'},
            ]
        },
            21: {//接通
                dialogue: [
                    {   speaker: '', 
                        position: 'right', 
                        avatar: 'img/1me.jpg', 
                        text: `怎樣！找我幹嘛？`, 
                    },
                    {   speaker: '', 
                        position: 'right', 
                        avatar: 'img/1me.jpg', 
                        text: `之前欠你的是都還清了嗎？`, 
                    },
                    {   speaker: '迪克', 
                        position: 'left', 
                        avatar: 'img/5ex.jpg', 
                        text: `是還了沒錯，但我沒說過不會有利息啊。`, 
                    },
                    {   speaker: '', 
                        position: 'right', 
                        avatar: 'img/1me.jpg', 
                        text: `當我傻了是不是。`, 
                    },
                    {   speaker: '迪克', 
                        position: 'left', 
                        avatar: 'img/5ex.jpg', 
                        text: `是傻了點，但不妨礙我繼續愛妳。`, 
                    },
                    {   speaker: '', 
                        position: 'center', 
                        avatar: '', 
                        text: `
                            《電話掛斷聲》
                            《電話掛斷聲》

                        《電話掛斷聲》

                            (臥室裡)
                            `, 
                    },
                    {   speaker: '段菲', 
                        position: 'left', 
                        avatar: 'img/2gf.jpg', 
                        text: `剛剛那通電話是誰啊？`, 
                    },
                ],
                options: [
                    {choice:'1', text: '含糊帶過'},
                    {choice:'3', text: '老實交代'},
                ]
            },
                211: {//含糊帶過 >BE
                    dialogue:[
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `沒啦，就之前一個朋友。`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `朋友會講這種話嗎？`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `就只是之前的朋友，連妳也要這樣嗎？`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `我哪樣？我是妳女友欸，不能知道嗎？`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `女友又怎樣？難道妳是我女友我一切事情就一定要跟妳說嗎？`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `妳一定要這個態度嗎？我們可以好好講的？`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `好好講？ 剛開始好好講不就好了。`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `妳這個態度我真的不知道怎麼跟妳溝通，之前就發生過一次了`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `受不了妳就走啊！沒人逼妳！`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `妳真的要說這種話嗎？既然這麼嫌棄的話，那我們就分手吧。`, 
                        },
                        {   speaker: '', 
                            position: 'center', 
                            avatar: '', 
                            text: `
                                    《關門聲》
                                    《關門聲》
                                    
                            《關門聲》
                                    
                            `, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `……`
                        },
                    ],
                    options: []
                },
                212: {//老實交代 >OE
                    dialogue:[
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `他是前男友，分手時發生點狀況，我砸破了一個古董花瓶，然後就被抓到尾巴了。`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `這樣也要計較，小氣的男人。`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `哈哈哈！就我們菲菲最大方。`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `當然啊！`, 
                        },
                    ],
                    options: []
                },                      
            22:{//掛斷
                dialogue:[
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `他是前男友，分手時發生點狀況，我砸破了一個古董花瓶，然後就被抓到尾巴了。`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `這樣也要計較，小氣的男人。`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `哈哈哈！就我們菲菲最大方。`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `當然啊`, 
                        },
                        {   speaker: '', 
                            position: 'center', 
                            avatar: '', 
                            text: ` 
                            （回家後）`,
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `菲菲閉上眼睛一下。`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `幹嘛～那麼神秘？`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `快點啦～`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `什麼啦？搞得好像要求婚一樣。`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `好了，睜開眼吧。`, 
                        },
                    //change求婚畫面
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `這！什麼啊！`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `段菲小姐，妳願意嫁給闕雲小姐嗎？`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `太突然了吧！`, 
                        },
                ],
                options: [
                        {choice:'1', text: '逗一下'},
                        {choice:'3', text: '認真的再問一次'},
                ]
            },                    
                221:{//逗一下>HE
                    dialogue:[
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `不要嗎？不要就算了。`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `欸欸欸！我願意！`, 
                        },
                    ],
                    options: []
                },                    
                222:{//認真的再問一次 >HE
                    dialogue:[
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `請問段菲小姐？妳願意嫁給闕雲小姐嗎？`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `我願意。`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `嘿嘿嘿，我也知道妳不會拒絕。`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `如果我拒絕呢？`, 
                        },
                        {   speaker: '', 
                            position: 'right', 
                            avatar: 'img/1me.jpg', 
                            text: `拒絕的話我就跪到妳答應啊！`, 
                        },
                        {   speaker: '段菲', 
                            position: 'left', 
                            avatar: 'img/2gf.jpg', 
                            text: `最好是。`, 
                        },
                    ],
                    options: []
                },
};
